### PR TITLE
Clean up `sprocket-csv.py` to make it more maintainable

### PR DESCRIPTION
**Pull request by LiaungYip**
The main changes are:

  * `settings.csv` is now a **comma** separated file, not a **semicolon** separated file. This makes it much easier to work on in Microsoft Excel, which expects CSV files to be comma-separated.
  * `sprocket-csv.py` was cleaned up and now uses field **names** (i.e. `row['.Ore.Name.']`) instead of field indexes i.e. `row[34]`. This makes it substantially easier to figure out what the code is doing.
  * A probable bug was removed where `sprocket-csv.py` was removing the first 19 rows of input without processing them.

### CODE REVIEW

**Comment by LiaungYip** [comment]
Sorry for the messy commit/revert history. I flubbed a few times.

**Comment by LiaungYip** [comment]
Also, https://github.com/LiaungYip/Sprocket/blob/commas-not-semicolons/settings.csv now renders as a beautiful table in GitHub!

**Comment by LiaungYip** [comment]
Finally, testing the original code, vs this revised code, gives **identical output**, except that the revised code does not skip the first 19 lines of the CSV file.

**Comment by lawremi** [comment]
Looks good. I think the CSV and INI files have diverged on this fork, so I'll have to fix that at some point. I found it easier to hack the INI files with an ordinary text editor, but we can switch back to CSV if users prefer spreadsheet interfaces. Also, I'm not sure if it's worth keeping the generated XML in the Sprocket repository. It would be nice if there were some sort of make system that would automatically go from CSV->INI->XML, perhaps installing the standard XML into a configured directory (like a COG working copy).

**Comment by LiaungYip** [comment]
Thanks for merge.

Regarding spreadsheet interfaces - the ODS spreadsheet is nice, because it does the parameter calculations for adding new ores. That makes it a lot easier for newcomers to contribute to / maintain this work. Just having the CSV / INI files makes the calculations mysterious and scary.

The ODS format specifically is a bit troublesome. I'm working on converting that to Excel format (which works in both Microsoft Excel and LibreOffice 5) and modifying `sprocket-csv.py` to work directly from the Excel file - eliminating the conversion to CSV. There's some discussion of that on https://github.com/reteo/Sprocket/issues/14 .

Agree that the XML files should not be tracked in git. I can work on a `make` system (probably another Python script) - I have a need for such a thing.

**Comment by lawremi** [comment]
Awesome, I'll look forward to it.

**Pull request merged**
